# Generated by Django 2.2.4 on 2021-11-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_detector', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tempItems',
        ),
    ]
