# Generated by Django 2.2.4 on 2021-11-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('face_detector', '0002_delete_tempitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
